# Generated by Django 4.1.3 on 2022-11-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default='', max_length=9),
        ),
    ]
